### ISSUE TITLE
Ninja Forms update failing

### ISSUE THREAD

**Issue by jeffwalker99** [parallelus/Plugin-Installer-for-Runway#24]
I think this problem is most likely related to the changes we've made to the plugin installer because I'm getting the error in the themes that have had the plugin installer extension updated.

I'm getting this error intermittently on live sandboxes and also my local sandboxes...

![2016-08-01_12-47-14](https://cloud.githubusercontent.com/assets/4571369/17293159/691ab370-57e6-11e6-94db-c4b95d8a527e.png)

By "intermittently" I mean that generally the first time I try to update Ninja Forms using this method it fails...

![2016-08-01_12-51-27](https://cloud.githubusercontent.com/assets/4571369/17293190/b8f8eaec-57e6-11e6-8978-6177a704e818.png)

If I try a second time, same method, sometimes it succeeds, other times it fails again.

Currently on the moregoexplore sandbox site I've tried four times and I keep getting the error, so you might like to give it a try and see for yourself?

**Comment by jeffwalker99** [comment]
I forgot to add that currently the moregoexplore sandbox is running an older version of the theme from before the recent plugin installer changes.

But I've this same problem with the latest versions of GoExplore! and FrontRunner.

**Comment by alexxgermann** [comment]
@jeffwalker99 
I could not reproduce the issue on the local server with the newest version of Plugin Installer from develop branch. Also, on http://imnoexpert.net/goexplore/ and http://imnoexpert.net/frontrunner/ the plugins are updated with no issues. I have noticed that the version 0.8.2 of Plugin Installer (instead of 0.9.2) is used on http://imnoexpert.net/moregoexplore/ . Please update Plugin Installer to the latest version on http://imnoexpert.net/moregoexplore/ and on your local sandbox and try to update plugins once again.

**Comment by jeffwalker99** [comment]
I had this problem with my GoExplore! and FrontRunner local sandbox sites, both of which are using the latest version of the theme, including v0.9.2 of the plugin installer. The first attempt to update fails with the "not found" error message, the second attempt succeeds.

**Comment by alexxgermann** [comment]
@jeffwalker99 
Did issue arise only upon attempting to update Ninja Forms or other plugins as well?

**Comment by jeffwalker99** [comment]
Only Ninja Forms so far. I'll do some more tests and get back to you.

**Comment by alexxgermann** [comment]
The error "Download failed. Not found" is displayed if "404 File not found" has been gotten as the response to http request for downloading an archive with the plugin. Upon attempting to update Ninja Forms WP core sends a request to URL https://downloads.wordpress.org/plugin/ninja-forms.2.9.54.zip. I have executed the request by this url few times in browser (outside WP) and for almost 30% of requests I got "404 File not found". So it makes me think that issue is on the external resource's side (https://downloads.wordpress.org), not our functionality

**Comment by jeffwalker99** [comment]
Yes, that was my initial thought. But I tried the https://downloads.wordpress.org/plugin/ninja-forms.2.9.54.zip URL several timers successfully, and afterwards on the moregoexplore sandbox site I got the "not found" error message again.

Perhaps we should leave this issue and see if any GoExplore!/FrontRunner/Caliber users report this problem.

**Comment by alexxgermann** [comment]
Ok, I'm agree with you

**Comment by jeffwalker99** [comment]
Okay, I'll flag this issue as "won't fix" and we can revisit later if needs be.

**Comment by jeffwalker99** [comment]
Closing this issue now as I can no longer replicate the problem and no customer has reported it.
