### ISSUE TITLE
Add fix for plugin names that include &#8211; (en dash) character

### ISSUE THREAD

**Issue by b-shtybin** [parallelus/Plugin-Installer-for-Runway#42]
Fix get parameters in Install url.

**Comment by b-shtybin** [comment]
@jeffwalker99
Could you please test?

**Comment by jeffwalker99** [comment]
This will get tested when we update themes with v0.9.8 of the plugin installer extension. But we know it works because we've made this change for the FrontRunner theme, so there shouldn't be a problem with this.

For the record - because a few months down the road we'll all have forgotten what this actually fixes 😃 - this fixes a problem with installing WP repo plugins when they have an en dash in their repo name, like the lite version of Beaver Builder does...

![2017-04-10_15-08-05](https://cloud.githubusercontent.com/assets/4571369/24865580/96e22998-1dff-11e7-8e0b-b553f742e558.png)

**Comment by jeffwalker99** [comment]
We also need to modify 'plugin-installer/js/field-extended.js' to deal with this en dash issue...

```
(function ($) {

    $(function () {
        var $buttons = $('.button-primary.ajax-save');

        $buttons.on('click', function () {
            $buttons
                .parent()
                .find('input')
                .attr('value', 'save');
        });

        $.each($('.plugin .install a'),function( i, val ) {
            var href = $(val).attr('href').replace('#8211;%20','&');
            $(val).attr('href',href);
        });
    });

})(jQuery);```
